on: push
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install yarn
        run: npm install --global yarn

      - name: yarn
        run: yarn

      - name: yarn build
        run: yarn build

      - name: Setup chrome
        uses: browser-actions/setup-chrome@v1

      - name: Pack extension
        run: cd chrome; chrome --pack-extension=$(Get-Location)

      - name: Change test variables to secrets
        run: (Get-Content ./tests/Tests/Tests.cs).Replace('{googleApiKey}', '${{secrets.GOOGLEAPIKEY}}') | Set-Content ./tests/Tests/Tests.cs; (Get-Content ./tests/Tests/Tests.cs).Replace('{deeplApiKey}', '${{secrets.DEEPLAPIKEY}}') | Set-Content ./tests/Tests/Tests.cs

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Build Tests
        run: cd tests; dotnet build

      - name: Run UnitTests
        run: dotnet test tests

      - name: Upload zipped archive
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: chrome
