on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install yarn
        run: npm install --global yarn

      - name: yarn
        run: yarn

      - name: yarn build
        run: yarn build

      - name: Change test variables to secrets
        run: sed 's/{googleApiKey}/${{secrets.GOOGLEAPIKEY}}/g' ./tests/Tests/Tests.cs; sed 's/{deeplApiKey}/${{secrets.DEEPLAPIKEY}}/g' ./tests/Tests/Tests.cs

      - name: Setup .NET SDK
        uses: actions/setup-dotnet

      - name: Run tests
        run: dotnet test ./tests/Tests/Tests.csproj

      - name: Upload zipped archive
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: chrome
