on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install yarn
        run: npm install --global yarn

      - name: yarn
        run: yarn

      - name: yarn build
        run: yarn build

      - name: Upload zipped archive
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: chrome